# Copyright (c) 2025-2026 weAIDB
# OpenCook: Start with a generic project. End with a perfectly tailored solution.
# SPDX-License-Identifier: MIT

from __future__ import annotations

from typing import TYPE_CHECKING

try:
    from typing import override
except ImportError:
    def override(func):
        return func

from code_agent.tools.base import Tool, ToolCallArguments, ToolExecResult, ToolParameter

if TYPE_CHECKING:
    from code_agent.agent.code_agent import CodeAgent


class PlanSubagentTool(Tool):
    """Generate the pseudo plans including the natural language functionality descriptions
    and potential function references for the intended code synthesis task."""

    def __init__(self, model_provider: str | None = None) -> None:
        super().__init__(model_provider)
        self._codeagent: CodeAgent | None = None  # set by CodeAgent.new_task()

    @override
    def get_model_provider(self) -> str | None:
        return self._model_provider

    @override
    def get_name(self) -> str:
        return "plan_subagent"

    @override
    def get_description(self) -> str:
        return (
            "Generate the pseudo plans including the natural language functionality descriptions "
            "and potential function references for the intended code synthesis task."
        )

    @override
    def get_parameters(self) -> list[ToolParameter]:
        return [
            ToolParameter(
                name="number",
                type="integer",
                description="The number of plans that requires to be generated by the planning agent.",
                required=True,
            ),
        ]

    @override
    async def execute(self, arguments: ToolCallArguments) -> ToolExecResult:
        if self._codeagent is None or self._codeagent.plan_agent is None:
            return ToolExecResult(
                error="PlanSubagentTool: _codeagent not set or has no plan_agent.",
                error_code=-1,
            )

        plan_agent = self._codeagent.plan_agent.agent
        task = self._codeagent._task
        extra_args = self._codeagent._extra_args

        try:
            number = int(arguments["number"]) if "number" in arguments else 1
        except (ValueError, TypeError):
            return ToolExecResult(
                error=f"Invalid value for 'number': {arguments.get('number')}",
                error_code=-1,
            )

        if number <= 0:
            return ToolExecResult(
                error="'number' must be a positive integer.",
                error_code=-1,
            )

        # Temporarily override _run_steps so get_processed_plan() generates
        # exactly `number` candidate plans, then restore the original value.
        original_run_steps = plan_agent._run_steps
        plan_agent._run_steps = number
        try:
            plan_str = await plan_agent.get_processed_plan(task, extra_args)
        finally:
            plan_agent._run_steps = original_run_steps

        if not plan_str or not plan_str.strip():
            return ToolExecResult(
                error="PlanAgent produced no valid plans.",
                error_code=-1,
            )

        return ToolExecResult(output=plan_str)
